spring.application.name=cafe-brewtopia
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=off

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n