spring.application.name=cafe-brewtopia
spring.datasource.url=jdbc:mysql://localhost:3306/cafe-brewtopia-db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=wnofkeqwhfqiewukrcjr3ljkuewfjotjut3gjikhvrg98o7jkfwtukf9y874jeikrtjku4fiuyght4987ijuhkfytn75fyj435y
jwt.expiration-ms=86400000

spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=off

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n